repos:
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv lock --check
        entry: uv lock --check
        language: python
        files: "^(pyproject.toml|uv.lock)$"
        pass_filenames: false
        additional_dependencies:
          - uv
